[env:xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

extra_scripts = pre:../extra_script.py
lib_extra_dirs = ../

lib_deps =
    sciot-common
    nanopb/Nanopb@^0.4.9
    knolleary/PubSubClient@^2.8

build_flags =
    -DWIFI_SSID=\"your-ssid\"
    -DWIFI_PASS=\"your-pass\"
    -DMQTT_HOST=\"192.168.1.10\"
    -DNODE_ID=\"example-01\"
