[env:xiao_esp32c3]
platform = espressif32
board = seeed_xiao_esp32c3
framework = arduino
monitor_speed = 115200

extra_scripts = pre:../extra_script.py
lib_extra_dirs = ../

lib_deps =
    sgh-common
    nanopb/Nanopb@^0.4.9
    knolleary/PubSubClient@^2.8
